/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "清风望月",
  "description": "这是我的个人博客",
  "base": "/blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/blog/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": null,
        "sidebar": false,
        "bgImage": "/logo.jpg",
        "bgImageStyle": {
          "height": "300px",
          "color": "#fff"
        }
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-ea6ed3cc",
      "path": "/",
      "lastUpdated": "12/14/2020, 1:55:59 PM"
    },
    {
      "title": "VuePress 搭建个人博客(2)",
      "frontmatter": {
        "title": "VuePress 搭建个人博客(2)",
        "lang": "zh-CN",
        "date": "2020-12-14T00:00:00.000Z",
        "categories": [
          "博客"
        ],
        "tags": [
          "blog"
        ],
        "publish": true
      },
      "regularPath": "/blogs/blog/Blog_2.html",
      "relativePath": "blogs/blog/Blog_2.md",
      "key": "v-6fcd6e3e",
      "path": "/blogs/blog/Blog_2.html",
      "headers": [
        {
          "level": 2,
          "title": "1. 编写你的第一篇博客文",
          "slug": "_1-编写你的第一篇博客文"
        },
        {
          "level": 2,
          "title": "2. 添加导航栏",
          "slug": "_2-添加导航栏"
        },
        {
          "level": 2,
          "title": "3. 添加左侧导航栏分类",
          "slug": "_3-添加左侧导航栏分类"
        }
      ],
      "excerpt": "<p>编写第一篇博客</p>\n",
      "lastUpdated": "2020/12/14 下午1:55:59"
    },
    {
      "title": "VuePress 搭建个人博客(1)",
      "frontmatter": {
        "title": "VuePress 搭建个人博客(1)",
        "lang": "zh-CN",
        "date": "2020-12-10T00:00:00.000Z",
        "sidebar": true,
        "subSidebar": true,
        "categories": [
          "博客"
        ],
        "tags": [
          "blog"
        ],
        "publish": true
      },
      "regularPath": "/blogs/blog/",
      "relativePath": "blogs/blog/README.md",
      "key": "v-15ff5a6a",
      "path": "/blogs/blog/",
      "headers": [
        {
          "level": 2,
          "title": "1. 安装 VuePress",
          "slug": "_1-安装-vuepress"
        },
        {
          "level": 2,
          "title": "2. 新建 docs 目录",
          "slug": "_2-新建-docs-目录"
        },
        {
          "level": 2,
          "title": "3. 新增 vuepress-theme-reco 插件",
          "slug": "_3-新增-vuepress-theme-reco-插件"
        },
        {
          "level": 2,
          "title": "4. 调整首页",
          "slug": "_4-调整首页"
        }
      ],
      "excerpt": "<p>从0开始教你如何 搭建你的个人博客</p>\n",
      "lastUpdated": "2020/12/14 下午1:55:59"
    },
    {
      "title": "git",
      "frontmatter": {
        "title": "git",
        "lang": "zh-CN",
        "date": "2021-01-22T00:00:00.000Z",
        "categories": [
          "git"
        ],
        "tags": [
          "git"
        ],
        "publish": true
      },
      "regularPath": "/blogs/git/",
      "relativePath": "blogs/git/README.md",
      "key": "v-1769d22a",
      "path": "/blogs/git/",
      "headers": [
        {
          "level": 2,
          "title": "1. git 拉取远程指定分支代码",
          "slug": "_1-git-拉取远程指定分支代码"
        }
      ],
      "excerpt": "",
      "lastUpdated": "2021/3/15 下午3:12:58"
    },
    {
      "title": "题目",
      "frontmatter": {
        "title": "题目",
        "date": "2020-12-14T00:00:00.000Z",
        "categories": [
          "前端"
        ],
        "tags": [
          "面试"
        ]
      },
      "regularPath": "/blogs/interview/",
      "relativePath": "blogs/interview/README.md",
      "key": "v-22311868",
      "path": "/blogs/interview/",
      "headers": [
        {
          "level": 2,
          "title": "1. 从输入url 到渲染出整个页面",
          "slug": "_1-从输入url-到渲染出整个页面"
        },
        {
          "level": 2,
          "title": "2. window.onload 和 DOMContentLoaded 的区别",
          "slug": "_2-window-onload-和-domcontentloaded-的区别"
        },
        {
          "level": 2,
          "title": "3. 前端安全",
          "slug": "_3-前端安全"
        },
        {
          "level": 2,
          "title": "4 常用数组方法",
          "slug": "_4-常用数组方法"
        },
        {
          "level": 3,
          "title": "4.1 常用方法",
          "slug": "_4-1-常用方法"
        },
        {
          "level": 3,
          "title": "4.2  纯函数方法",
          "slug": "_4-2-纯函数方法"
        },
        {
          "level": 2,
          "title": "5 自定义v-model",
          "slug": "_5-自定义v-model"
        },
        {
          "level": 2,
          "title": "6 动态组件",
          "slug": "_6-动态组件"
        },
        {
          "level": 2,
          "title": "7 异步加载组件",
          "slug": "_7-异步加载组件"
        },
        {
          "level": 2,
          "title": "8 缓存",
          "slug": "_8-缓存"
        },
        {
          "level": 2,
          "title": "9 Object.definePrototype 的实现原理",
          "slug": "_9-object-defineprototype-的实现原理"
        },
        {
          "level": 2,
          "title": "10 用js 模拟DOM 结构",
          "slug": "_10-用js-模拟dom-结构"
        }
      ],
      "lastUpdated": "1/22/2021, 10:40:07 AM"
    },
    {
      "title": "实用",
      "frontmatter": {
        "title": "实用",
        "lang": "zh-CN",
        "date": "2021-02=19",
        "categories": [
          "实用"
        ],
        "tags": [
          "实用"
        ],
        "publish": true
      },
      "regularPath": "/blogs/practical/",
      "relativePath": "blogs/practical/README.md",
      "key": "v-138220a4",
      "path": "/blogs/practical/",
      "headers": [
        {
          "level": 2,
          "title": "1 win10 激活",
          "slug": "_1-win10-激活"
        },
        {
          "level": 2,
          "title": "2 解决 github 无法访问问题",
          "slug": "_2-解决-github-无法访问问题"
        }
      ],
      "lastUpdated": "2021/4/25 上午10:45:41"
    },
    {
      "title": "手写系列",
      "frontmatter": {
        "title": "手写系列",
        "lang": "zh-CN",
        "date": "2020-12-14T00:00:00.000Z",
        "categories": [
          "前端"
        ],
        "tags": [
          "js",
          "手写"
        ],
        "publish": true
      },
      "regularPath": "/blogs/js/",
      "relativePath": "blogs/js/README.md",
      "key": "v-7d15af6c",
      "path": "/blogs/js/",
      "headers": [
        {
          "level": 2,
          "title": "1 防抖",
          "slug": "_1-防抖"
        },
        {
          "level": 2,
          "title": "2 节流",
          "slug": "_2-节流"
        },
        {
          "level": 2,
          "title": "3 深度拷贝",
          "slug": "_3-深度拷贝"
        },
        {
          "level": 2,
          "title": "4 深度比较",
          "slug": "_4-深度比较"
        },
        {
          "level": 2,
          "title": "5 拍平多维数组",
          "slug": "_5-拍平多维数组"
        },
        {
          "level": 2,
          "title": "6 一维转多维",
          "slug": "_6-一维转多维"
        },
        {
          "level": 2,
          "title": "7 手写 call aplly bind 同理",
          "slug": "_7-手写-call-aplly-bind-同理"
        },
        {
          "level": 2,
          "title": "8 js 原生 copy 的实现",
          "slug": "_8-js-原生-copy-的实现"
        },
        {
          "level": 2,
          "title": "9 取 url 参数",
          "slug": "_9-取-url-参数"
        },
        {
          "level": 2,
          "title": "10 快速生成数组",
          "slug": "_10-快速生成数组"
        },
        {
          "level": 2,
          "title": "11 正则最多几位小数 小数点未超过，也不补充",
          "slug": "_11-正则最多几位小数-小数点未超过-也不补充"
        }
      ],
      "lastUpdated": "2021/7/7 下午3:16:36"
    },
    {
      "title": "vue",
      "frontmatter": {
        "title": "vue",
        "lang": "zh-CN",
        "date": "2021-02=19",
        "categories": [
          "vue修饰符"
        ],
        "tags": [
          "vue"
        ],
        "publish": true
      },
      "regularPath": "/blogs/vue/",
      "relativePath": "blogs/vue/README.md",
      "key": "v-74056dc2",
      "path": "/blogs/vue/",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "1.lazy",
          "slug": "_1-lazy"
        },
        {
          "level": 2,
          "title": "2.trim",
          "slug": "_2-trim"
        },
        {
          "level": 2,
          "title": "3.number",
          "slug": "_3-number"
        },
        {
          "level": 2,
          "title": "4.stop",
          "slug": "_4-stop"
        },
        {
          "level": 2,
          "title": "5.capture",
          "slug": "_5-capture"
        },
        {
          "level": 2,
          "title": "6.self",
          "slug": "_6-self"
        },
        {
          "level": 2,
          "title": "7.once",
          "slug": "_7-once"
        },
        {
          "level": 2,
          "title": "8.prevent",
          "slug": "_8-prevent"
        },
        {
          "level": 2,
          "title": "9.native",
          "slug": "_9-native"
        },
        {
          "level": 2,
          "title": "10.left，right，middle",
          "slug": "_10-left-right-middle"
        },
        {
          "level": 2,
          "title": "11.passive",
          "slug": "_11-passive"
        },
        {
          "level": 2,
          "title": "12.camel",
          "slug": "_12-camel"
        },
        {
          "level": 2,
          "title": "12.sync",
          "slug": "_12-sync"
        },
        {
          "level": 2,
          "title": "13.keyCode",
          "slug": "_13-keycode"
        },
        {
          "level": 2,
          "title": "结语",
          "slug": "结语"
        }
      ],
      "lastUpdated": "2020/12/16 上午10:16:52"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "blog Tags"
      },
      "regularPath": "/tag/blog/",
      "key": "v-1559f73a",
      "path": "/tag/blog/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "git Tags"
      },
      "regularPath": "/tag/git/",
      "key": "v-32383f72",
      "path": "/tag/git/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "面试 Tags"
      },
      "regularPath": "/tag/%E9%9D%A2%E8%AF%95/",
      "key": "v-6018b856",
      "path": "/tag/面试/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "实用 Tags"
      },
      "regularPath": "/tag/%E5%AE%9E%E7%94%A8/",
      "key": "v-d2283362",
      "path": "/tag/实用/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "js Tags"
      },
      "regularPath": "/tag/js/",
      "key": "v-e8d86dc8",
      "path": "/tag/js/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "手写 Tags"
      },
      "regularPath": "/tag/%E6%89%8B%E5%86%99/",
      "key": "v-de8294a6",
      "path": "/tag/手写/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "vue Tags"
      },
      "regularPath": "/tag/vue/",
      "key": "v-322a45da",
      "path": "/tag/vue/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "博客 Categories"
      },
      "regularPath": "/categories/%E5%8D%9A%E5%AE%A2/",
      "key": "v-42aee080",
      "path": "/categories/博客/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "git Categories"
      },
      "regularPath": "/categories/git/",
      "key": "v-7f0f18bb",
      "path": "/categories/git/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端 Categories"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF/",
      "key": "v-14bbbf36",
      "path": "/categories/前端/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "实用 Categories"
      },
      "regularPath": "/categories/%E5%AE%9E%E7%94%A8/",
      "key": "v-6202375b",
      "path": "/categories/实用/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "vue修饰符 Categories"
      },
      "regularPath": "/categories/vue%E4%BF%AE%E9%A5%B0%E7%AC%A6/",
      "key": "v-afeae2e8",
      "path": "/categories/vue修饰符/"
    }
  ],
  "themeConfig": {
    "codeTheme": "okaidia",
    "type": "blog",
    "author": "赵宇",
    "subSidebar": "auto",
    "authorAvatar": "/logo.jpg",
    "noFoundPageByTencent": false,
    "repo": "https://github.com/ZhaoYu8/blog.git",
    "lastUpdated": "最后更新日期",
    "valineConfig": {
      "appId": "6ckqcRikE5B7Whz1XOd9vDNI-9Nh9j0Va",
      "appKey": "th9r6f11BRI4ehLHc9vrA9XA",
      "placeholder": "请输入你的意见",
      "avatar": "wavatar",
      "enableQQ": true
    },
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "目录索引",
        "icon": "reco-home",
        "items": [
          {
            "text": "js",
            "link": "/categories/前端/"
          }
        ]
      },
      {
        "text": "时间轴",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "常用链接",
        "items": [
          {
            "text": "vuepress文档",
            "link": "https://www.vuepress.cn/guide/"
          },
          {
            "text": "reco 插件文档",
            "link": "https://vuepress-theme-reco.recoluan.com/views/1.x/installUse.html"
          }
        ]
      }
    ],
    "sidebar": {
      "/blogs/blog/": [
        {
          "title": "搭建个人博客",
          "collapsable": true,
          "path": "/blogs/blog/",
          "children": [
            {
              "title": "1. 搭建一个漂亮的个人博客",
              "path": "/blogs/blog/"
            },
            {
              "title": "2. 编写第一篇博客",
              "path": "/blogs/blog/Blog_2"
            }
          ]
        }
      ],
      "/blogs/js": [
        {
          "title": "js",
          "collapsable": true,
          "path": "/blogs/js/",
          "children": [
            {
              "title": "手写方法",
              "path": "/blogs/js/"
            }
          ]
        }
      ]
    }
  }
}