/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "blog": {
      "key": "blog",
      "scope": "tags",
      "path": "/tag/blog/",
      "pageKeys": [
        "v-6fcd6e3e",
        "v-15ff5a6a"
      ]
    },
    "git": {
      "key": "git",
      "scope": "tags",
      "path": "/tag/git/",
      "pageKeys": [
        "v-1769d22a"
      ]
    },
    "面试": {
      "key": "面试",
      "scope": "tags",
      "path": "/tag/面试/",
      "pageKeys": [
        "v-22311868"
      ]
    },
    "实用": {
      "key": "实用",
      "scope": "tags",
      "path": "/tag/实用/",
      "pageKeys": [
        "v-138220a4"
      ]
    },
    "js": {
      "key": "js",
      "scope": "tags",
      "path": "/tag/js/",
      "pageKeys": [
        "v-7d15af6c"
      ]
    },
    "手写": {
      "key": "手写",
      "scope": "tags",
      "path": "/tag/手写/",
      "pageKeys": [
        "v-7d15af6c"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-74056dc2"
      ]
    }
  },
  "categories": {
    "博客": {
      "key": "博客",
      "scope": "categories",
      "path": "/categories/博客/",
      "pageKeys": [
        "v-6fcd6e3e",
        "v-15ff5a6a"
      ]
    },
    "git": {
      "key": "git",
      "scope": "categories",
      "path": "/categories/git/",
      "pageKeys": [
        "v-1769d22a"
      ]
    },
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-22311868",
        "v-7d15af6c"
      ]
    },
    "实用": {
      "key": "实用",
      "scope": "categories",
      "path": "/categories/实用/",
      "pageKeys": [
        "v-138220a4"
      ]
    },
    "vue修饰符": {
      "key": "vue修饰符",
      "scope": "categories",
      "path": "/categories/vue修饰符/",
      "pageKeys": [
        "v-74056dc2"
      ]
    }
  },
  "timeline": {}
}